---
- name: Install php_mongo
  shell: "{{ item }}"
  with_items:
    - wget https://github.com/mongodb/mongo-php-driver/archive/{{ php_mongo_version }}.tar.gz
    - tar xzf {{ php_mongo_version }}.tar.gz
    - cd mongo-php-driver-{{ php_mongo_version }}
    - phpize
    - ./configure
    - make
    - make install
    - cd ..
    - rm mongo-php-driver-{{ php_mongo_version }} -R
    - rm {{ php_mongo_version }}.tar.gz
    - mv /etc/php5/mods-available/mongo.ini /etc/php5/mods-available/mongo.bkp
    - touch /etc/php5/mods-available/mongo.ini
    - echo "extension=mongo.so" > /etc/php5/mods-available/mongo.ini
    - ln -s /etc/php5/mods-available/mongo.ini /etc/php5/apache2/conf.d/mongo.ini
    - ln -s /etc/php5/mods-available/mongo.ini /etc/php5/fpm/conf.d/mongo.ini
  notify: restart nginx
